### ISSUE TITLE
Getting this error while running python script

### ISSUE THREAD

**Issue by stalluri** [neptuneio/usecase-templates#1]
Processing  47  use cases.
Processing  /Users/satish/OneDrive/Documents/Neptune/workspace/usecase-templates/amazon_dynamodb/scale_down_dynamodb_table_when_consumed_capacity_is_low.json
Traceback (most recent call last):
  File "./generate_use_cases_metadata.py", line 28, in <module>
    data = json.load(data_file)
  File "/Library/Python/2.7/site-packages/simplejson/**init**.py", line 459, in load
    use_decimal=use_decimal, **kw)
  File "/Library/Python/2.7/site-packages/simplejson/**init**.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/Library/Python/2.7/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/Library/Python/2.7/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 17 column 21 (char 628)

**Comment by buchireddy** [comment]
Make sure /Users/satish/OneDrive/Documents/Neptune/workspace/usecase-templates/amazon_dynamodb/scale_down_dynamodb_table_when_consumed_capacity_is_low.json is a valid JSON.
